
package ucoach.data.internal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CoachService", targetNamespace = "http://ws.data.ucoach/", wsdlLocation = "http://ucoach-internal-data-service.herokuapp.com/ws/coach?wsdl")
public class CoachService
    extends Service
{

    private final static URL COACHSERVICE_WSDL_LOCATION;
    private final static WebServiceException COACHSERVICE_EXCEPTION;
    private final static QName COACHSERVICE_QNAME = new QName("http://ws.data.ucoach/", "CoachService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ucoach-internal-data-service.herokuapp.com/ws/coach?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COACHSERVICE_WSDL_LOCATION = url;
        COACHSERVICE_EXCEPTION = e;
    }

    public CoachService() {
        super(__getWsdlLocation(), COACHSERVICE_QNAME);
    }

    public CoachService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COACHSERVICE_QNAME, features);
    }

    public CoachService(URL wsdlLocation) {
        super(wsdlLocation, COACHSERVICE_QNAME);
    }

    public CoachService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COACHSERVICE_QNAME, features);
    }

    public CoachService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoachService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CoachInterface
     */
    @WebEndpoint(name = "CoachServicePort")
    public CoachInterface getCoachServicePort() {
        return super.getPort(new QName("http://ws.data.ucoach/", "CoachServicePort"), CoachInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoachInterface
     */
    @WebEndpoint(name = "CoachServicePort")
    public CoachInterface getCoachServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.data.ucoach/", "CoachServicePort"), CoachInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COACHSERVICE_EXCEPTION!= null) {
            throw COACHSERVICE_EXCEPTION;
        }
        return COACHSERVICE_WSDL_LOCATION;
    }

}
