
package ucoach.data.internal.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoachInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoachInterface {


    /**
     * 
     * @param coachId
     * @return
     *     returns ucoach.data.internal.ws.Coach
     */
    @WebMethod
    @WebResult(name = "coach", targetNamespace = "")
    @RequestWrapper(localName = "getCoach", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetCoach")
    @ResponseWrapper(localName = "getCoachResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetCoachResponse")
    @Action(input = "http://ws.data.ucoach/CoachInterface/getCoachRequest", output = "http://ws.data.ucoach/CoachInterface/getCoachResponse")
    public Coach getCoach(
        @WebParam(name = "coachId", targetNamespace = "")
        int coachId);

    /**
     * 
     * @param coach
     * @return
     *     returns ucoach.data.internal.ws.Coach
     */
    @WebMethod
    @WebResult(name = "createdCoach", targetNamespace = "")
    @RequestWrapper(localName = "createCoach", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateCoach")
    @ResponseWrapper(localName = "createCoachResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateCoachResponse")
    @Action(input = "http://ws.data.ucoach/CoachInterface/createCoachRequest", output = "http://ws.data.ucoach/CoachInterface/createCoachResponse")
    public Coach createCoach(
        @WebParam(name = "coach", targetNamespace = "")
        Coach coach);

    /**
     * 
     * @param coach
     * @return
     *     returns ucoach.data.internal.ws.Coach
     */
    @WebMethod
    @WebResult(name = "updateCoach", targetNamespace = "")
    @RequestWrapper(localName = "updateCoach", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.UpdateCoach")
    @ResponseWrapper(localName = "updateCoachResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.UpdateCoachResponse")
    @Action(input = "http://ws.data.ucoach/CoachInterface/updateCoachRequest", output = "http://ws.data.ucoach/CoachInterface/updateCoachResponse")
    public Coach updateCoach(
        @WebParam(name = "coach", targetNamespace = "")
        Coach coach);

    /**
     * 
     * @param coachId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCoach", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteCoach")
    @ResponseWrapper(localName = "deleteCoachResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteCoachResponse")
    @Action(input = "http://ws.data.ucoach/CoachInterface/deleteCoachRequest", output = "http://ws.data.ucoach/CoachInterface/deleteCoachResponse")
    public void deleteCoach(
        @WebParam(name = "coachId", targetNamespace = "")
        int coachId);

}
