
package ucoach.data.internal.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GoalInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GoalInterface {


    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalFromUser", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUser", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUser")
    @ResponseWrapper(localName = "getGoalsFromUserResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserResponse")
    public List<Goal> getGoalsFromUser(
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param dueDate
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalsFromUserAfterDueDate", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUserAfterDueDate", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserAfterDueDate")
    @ResponseWrapper(localName = "getGoalsFromUserAfterDueDateResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserAfterDueDateResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserAfterDueDateRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserAfterDueDateResponse")
    public List<Goal> getGoalsFromUserAfterDueDate(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "dueDate", targetNamespace = "")
        String dueDate);

    /**
     * 
     * @param dueDate
     * @param userId
     * @param frequency
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalsFromUserByFrequencyAndDueDate", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUserByFrequencyAndDueDate", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByFrequencyAndDueDate")
    @ResponseWrapper(localName = "getGoalsFromUserByFrequencyAndDueDateResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByFrequencyAndDueDateResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByFrequencyAndDueDateRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByFrequencyAndDueDateResponse")
    public List<Goal> getGoalsFromUserByFrequencyAndDueDate(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "frequency", targetNamespace = "")
        String frequency,
        @WebParam(name = "dueDate", targetNamespace = "")
        String dueDate);

    /**
     * 
     * @param goal
     * @param hmTypeId
     * @param userId
     * @return
     *     returns ucoach.data.internal.ws.Goal
     */
    @WebMethod
    @WebResult(name = "createdGoal", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateGoalResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/createGoalRequest", output = "http://ws.data.ucoach/GoalInterface/createGoalResponse")
    public Goal createGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal,
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param goalId
     * @return
     *     returns ucoach.data.internal.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "achieveGoal", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.AchieveGoal")
    @ResponseWrapper(localName = "achieveGoalResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.AchieveGoalResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/achieveGoalRequest", output = "http://ws.data.ucoach/GoalInterface/achieveGoalResponse")
    public Goal achieveGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

    /**
     * 
     * @param goalId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteGoalResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/deleteGoalRequest", output = "http://ws.data.ucoach/GoalInterface/deleteGoalResponse")
    public void deleteGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

    /**
     * 
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalFromUserByType", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUserByType", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByType")
    @ResponseWrapper(localName = "getGoalsFromUserByTypeResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByTypeResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByTypeRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByTypeResponse")
    public List<Goal> getGoalsFromUserByType(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param achieved
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalFromUserByTypeAndStatus", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUserByTypeAndStatus", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByTypeAndStatus")
    @ResponseWrapper(localName = "getGoalsFromUserByTypeAndStatusResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByTypeAndStatusResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByTypeAndStatusRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByTypeAndStatusResponse")
    public List<Goal> getGoalsFromUserByTypeAndStatus(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId,
        @WebParam(name = "achieved", targetNamespace = "")
        int achieved);

}
