
package ucoach.data.internal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GoalService", targetNamespace = "http://ws.data.ucoach/", wsdlLocation = "http://192.168.0.102:6900/ws/goal?wsdl")
public class GoalService
    extends Service
{

    private final static URL GOALSERVICE_WSDL_LOCATION;
    private final static WebServiceException GOALSERVICE_EXCEPTION;
    private final static QName GOALSERVICE_QNAME = new QName("http://ws.data.ucoach/", "GoalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.102:6900/ws/goal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GOALSERVICE_WSDL_LOCATION = url;
        GOALSERVICE_EXCEPTION = e;
    }

    public GoalService() {
        super(__getWsdlLocation(), GOALSERVICE_QNAME);
    }

    public GoalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GOALSERVICE_QNAME, features);
    }

    public GoalService(URL wsdlLocation) {
        super(wsdlLocation, GOALSERVICE_QNAME);
    }

    public GoalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GOALSERVICE_QNAME, features);
    }

    public GoalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GoalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GoalInterface
     */
    @WebEndpoint(name = "GoalServicePort")
    public GoalInterface getGoalServicePort() {
        return super.getPort(new QName("http://ws.data.ucoach/", "GoalServicePort"), GoalInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GoalInterface
     */
    @WebEndpoint(name = "GoalServicePort")
    public GoalInterface getGoalServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.data.ucoach/", "GoalServicePort"), GoalInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GOALSERVICE_EXCEPTION!= null) {
            throw GOALSERVICE_EXCEPTION;
        }
        return GOALSERVICE_WSDL_LOCATION;
    }

}
