
package ucoach.data.internal.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GoalInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GoalInterface {


    /**
     * 
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "GoalFromUserByType", targetNamespace = "")
    @RequestWrapper(localName = "getGoalsFromUserByHMType", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByHMType")
    @ResponseWrapper(localName = "getGoalsFromUserByHMTypeResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetGoalsFromUserByHMTypeResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByHMTypeRequest", output = "http://ws.data.ucoach/GoalInterface/getGoalsFromUserByHMTypeResponse")
    public List<Goal> getGoalsFromUserByHMType(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param goal
     * @param hmTypeId
     * @param userId
     * @return
     *     returns ucoach.data.internal.ws.Goal
     */
    @WebMethod
    @WebResult(name = "createdGoal", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateGoalResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/createGoalRequest", output = "http://ws.data.ucoach/GoalInterface/createGoalResponse")
    public Goal createGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal,
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param goalId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteGoalResponse")
    @Action(input = "http://ws.data.ucoach/GoalInterface/deleteGoalRequest", output = "http://ws.data.ucoach/GoalInterface/deleteGoalResponse")
    public void deleteGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        int goalId);

}
