
package ucoach.data.internal.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthMeasureInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthMeasureInterface {


    /**
     * 
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HmType>
     */
    @WebMethod
    @WebResult(name = "HMType", targetNamespace = "")
    @RequestWrapper(localName = "getHMTypes", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHMTypes")
    @ResponseWrapper(localName = "getHMTypesResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHMTypesResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesResponse")
    public List<HmType> getHMTypes();

    /**
     * 
     * @param fromDate
     * @param toDate
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasureFromUserByTypeBetweenDates", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasuresFromUserByTypeBetweenDates", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByTypeBetweenDates")
    @ResponseWrapper(localName = "getHealthMeasuresFromUserByTypeBetweenDatesResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByTypeBetweenDatesResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeBetweenDatesRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeBetweenDatesResponse")
    public List<HealthMeasure> getHealthMeasuresFromUserByTypeBetweenDates(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId,
        @WebParam(name = "fromDate", targetNamespace = "")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "")
        String toDate);

    /**
     * 
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasureFromUserByType", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasuresFromUserByType", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByType")
    @ResponseWrapper(localName = "getHealthMeasuresFromUserByTypeResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByTypeResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeResponse")
    public List<HealthMeasure> getHealthMeasuresFromUserByType(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param afterDate
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasureFromUserByTypeAfterDate", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasuresFromUserByTypeAfterDate", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByTypeAfterDate")
    @ResponseWrapper(localName = "getHealthMeasuresFromUserByTypeAfterDateResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByTypeAfterDateResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeAfterDateRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByTypeAfterDateResponse")
    public List<HealthMeasure> getHealthMeasuresFromUserByTypeAfterDate(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId,
        @WebParam(name = "afterDate", targetNamespace = "")
        String afterDate);

    /**
     * 
     * @param healthMeasure
     * @param hmTypeId
     * @param userId
     * @return
     *     returns ucoach.data.internal.ws.HealthMeasure
     */
    @WebMethod
    @WebResult(name = "createdHealthMeasure", targetNamespace = "")
    @RequestWrapper(localName = "createHealthMeasure", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateHealthMeasure")
    @ResponseWrapper(localName = "createHealthMeasureResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateHealthMeasureResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/createHealthMeasureRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/createHealthMeasureResponse")
    public HealthMeasure createHealthMeasure(
        @WebParam(name = "healthMeasure", targetNamespace = "")
        HealthMeasure healthMeasure,
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param healthMeasureId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHealthMeasure", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteHealthMeasure")
    @ResponseWrapper(localName = "deleteHealthMeasureResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteHealthMeasureResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/deleteHealthMeasureRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/deleteHealthMeasureResponse")
    public void deleteHealthMeasure(
        @WebParam(name = "healthMeasureId", targetNamespace = "")
        int healthMeasureId);

}
