
package ucoach.data.internal.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthMeasureInterface", targetNamespace = "http://ws.data.ucoach/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthMeasureInterface {


    /**
     * 
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HmType>
     */
    @WebMethod
    @WebResult(name = "HMType", targetNamespace = "")
    @RequestWrapper(localName = "getHMTypes", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHMTypes")
    @ResponseWrapper(localName = "getHMTypesResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHMTypesResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHMTypesResponse")
    public List<HmType> getHMTypes();

    /**
     * 
     * @param hmTypeId
     * @param userId
     * @return
     *     returns java.util.List<ucoach.data.internal.ws.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasureFromUserByType", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasuresFromUserByHMType", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByHMType")
    @ResponseWrapper(localName = "getHealthMeasuresFromUserByHMTypeResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.GetHealthMeasuresFromUserByHMTypeResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByHMTypeRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/getHealthMeasuresFromUserByHMTypeResponse")
    public List<HealthMeasure> getHealthMeasuresFromUserByHMType(
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param healthMeasure
     * @param hmTypeId
     * @param userId
     * @return
     *     returns ucoach.data.internal.ws.HealthMeasure
     */
    @WebMethod
    @WebResult(name = "createdHealthMeasure", targetNamespace = "")
    @RequestWrapper(localName = "createHealthMeasure", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateHealthMeasure")
    @ResponseWrapper(localName = "createHealthMeasureResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.CreateHealthMeasureResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/createHealthMeasureRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/createHealthMeasureResponse")
    public HealthMeasure createHealthMeasure(
        @WebParam(name = "healthMeasure", targetNamespace = "")
        HealthMeasure healthMeasure,
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "hmTypeId", targetNamespace = "")
        int hmTypeId);

    /**
     * 
     * @param healthMeasureId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHealthMeasure", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteHealthMeasure")
    @ResponseWrapper(localName = "deleteHealthMeasureResponse", targetNamespace = "http://ws.data.ucoach/", className = "ucoach.data.internal.ws.DeleteHealthMeasureResponse")
    @Action(input = "http://ws.data.ucoach/HealthMeasureInterface/deleteHealthMeasureRequest", output = "http://ws.data.ucoach/HealthMeasureInterface/deleteHealthMeasureResponse")
    public void deleteHealthMeasure(
        @WebParam(name = "healthMeasureId", targetNamespace = "")
        int healthMeasureId);

}
